baseURL = "https://ahmedakef.github.io/"
languageCode = "en-us"
title = "Ahmed Akef"
theme = "ronu-hugo-theme"
paginate = 8
ignoreFiles = [ "LICENSE$" ]
googleAnalytics = "G-6K1SEDG5LZ"

[params]
  mainSections = ["posts"]
  description = "Ahmed Akef trying to spread the little knowlade he gains."


[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2

[author]
	name = "Your Name"
	twitterURL = "https://twitter.com/ahmed_akef_"
	githubURL = "https://github.com/ahmedakef"
	linkedinURL = "https://www.linkedin.com/in/ahmedakef4"
	email = "aemed.akef.1@gmail.com"


