baseURL = "https://ahmedakef.github.io"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
ignoreFiles = [ "LICENSE$" ]

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  #contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ahmed_akef_"

  [[params.social]]
    name = "email"
    url  = "mailto:aemed.akef.1@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ahmedakef"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/ahmedakef4"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/5166590/ahmedakef"


[author]
    name = "Ahmed Akef"
    github = "ahmedakef"
    linkedin = "ahmedakef4"
    twitter = "ahmed_akef_"

[languages]
  [languages.en]
    title = "Ahmed Akef"
    subtitle = "Coder and Computer Enthusiast"
    keywords = ""
    description = "Ahmed Akef trying to spread the little knowlade he gains."
    copyright = "<p>Copyright © 2022 Ahmed Akef</p><p xmlns:dct='http://purl.org/dc/terms/' xmlns:cc='http://creativecommons.org/ns#' class='license-text'><a rel='cc:attributionURL' property='dct:title' href='https://github.com/ahmedakef/ahmedakef.github.io'>Content</a> licensed under <a rel='license' href='https://creativecommons.org/licenses/by/4.0'>CC BY 4.0</a></p>"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    #lastModDisplay = "modified"

    [languages.en.params.logo]
      logoText = "ahmed akef"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
