baseURL = "https://ahmedakef.github.io/"
languageCode = "en-us"
title = "Ahmed Akef"
theme = "ronu-hugo-theme"
paginate = 8
ignoreFiles = [ "LICENSE$" ]
images = ['img/owl.png']
googleAnalytics = "G-6K1SEDG5LZ"

[params]
  mainSections = ["posts"]
  description = "Ahmed Akef trying to spread the little knowlade he gains."


[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1


[author]
	name = "Your Name"
	twitterURL = "https://twitter.com/ahmed_akef_"
	githubURL = "https://github.com/ahmedakef"
	linkedinURL = "https://www.linkedin.com/in/ahmedakef4"
	email = "aemed.akef.1@gmail.com"

[params.comments]
	enabled = true
	engine = "cactus"
	gitHubRepo = "ahmedakef/ahmedakef.github.io"
	cactusSiteName = "ahmedakef"


